"""add table New_Capacity

Revision ID: 0b5c1e687a03
Revises: d3662ca84d7b
Create Date: 2021-10-17 16:05:14.963670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b5c1e687a03'
down_revision = 'd3662ca84d7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('new__capacity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('condenser_id', sa.Integer(), nullable=True),
    sa.Column('max_temp', sa.Integer(), nullable=True),
    sa.Column('min_temp', sa.Integer(), nullable=True),
    sa.Column('capacity_point', sa.Float(), nullable=True),
    sa.Column('delta_temp', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['condenser_id'], ['condenser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('new__capacity')
    # ### end Alembic commands ###
