"""Full version

Revision ID: 3f8f316e0fa9
Revises: 71a30cc30af2
Create Date: 2021-09-29 11:11:30.535081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f8f316e0fa9'
down_revision = '71a30cc30af2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auto', sa.Column('count_rent', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auto', 'count_rent')
    # ### end Alembic commands ###
