"""Add Freon table

Revision ID: 94279cf3f3ed
Revises: 0b5c1e687a03
Create Date: 2022-02-20 07:40:51.610419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94279cf3f3ed'
down_revision = '0b5c1e687a03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('freon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('coef', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('freon')
    # ### end Alembic commands ###
