"""check name

Revision ID: d3662ca84d7b
Revises: 
Create Date: 2021-10-04 23:21:27.983153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3662ca84d7b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('condenser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('fan', sa.String(length=128), nullable=True),
    sa.Column('number_fan', sa.Integer(), nullable=True),
    sa.Column('air_flow', sa.Integer(), nullable=True),
    sa.Column('noise', sa.Integer(), nullable=True),
    sa.Column('low_noise', sa.Boolean(), nullable=True),
    sa.Column('img_url_1', sa.String(length=128), nullable=True),
    sa.Column('img_url_2', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('capacity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('condenser_id', sa.Integer(), nullable=True),
    sa.Column('max_temp', sa.Integer(), nullable=True),
    sa.Column('min_temp', sa.Integer(), nullable=True),
    sa.Column('capacity_point', sa.Float(), nullable=True),
    sa.Column('delta_temp', sa.Integer(), nullable=True),
    sa.Column('check_name', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['condenser_id'], ['condenser.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('check_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('capacity')
    op.drop_table('condenser')
    # ### end Alembic commands ###
