"""add time string

Revision ID: d54ab97cb951
Revises: 3f8f316e0fa9
Create Date: 2021-09-29 13:26:33.062287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd54ab97cb951'
down_revision = '3f8f316e0fa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auto', sa.Column('time_str', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auto', 'time_str')
    # ### end Alembic commands ###
