"""Initial migration.

Revision ID: e167abcb2827
Revises: 
Create Date: 2021-09-23 12:07:30.569920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e167abcb2827'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('transmission', sa.Boolean(), nullable=True),
    sa.Column('img_url_1', sa.String(length=128), nullable=True),
    sa.Column('img_url_2', sa.String(length=128), nullable=True),
    sa.Column('img_url_3', sa.String(length=128), nullable=True),
    sa.Column('img_url_4', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auto')
    # ### end Alembic commands ###
