"""Full app

Revision ID: edadd1b7192f
Revises: d54ab97cb951
Create Date: 2021-09-29 13:32:22.197257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edadd1b7192f'
down_revision = 'd54ab97cb951'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auto', 'time_str')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auto', sa.Column('time_str', sa.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
